---
title: "Taylor_Decay"
author: "Nick Borcherding"
date: "4/5/2022"
output: html_document
---

#Set-Up

### Loading Library

This block of code will check if you have the necessary packages installed to run the functions and load them into your environment.
```{r include=FALSE}
packages=c("scales", "dplyr", "Rtsne", "ggplot2", "RColorBrewer", "broom", "tidyr", "corrr", "tidygraph", "limma", "ggrepel", "reshape2", "ggraph", "readxl", "npreg")

installed = rownames(installed.packages())

for (pkg in packages) {
    if (! pkg %in% installed) {
        install.packages(pkg)
    }
}
invisible(lapply(packages, library, character.only = TRUE))

source("./R/functions.r") #Loads Sidak-Holm approach for multiple hypothesis correction
```


### Loading Data

```{r}
Liver <- readxl::read_xlsx("./data/220303_TaylorLab_Hypoxia_Liver_AJR.xlsx")[,-255]
colnames(Liver)[254] <- "Valine" #2 valine measurements, removing the second


path <- list.files("./data/metabolicPathways")
pathways <- NULL
for (i in seq_along(path)) {
  pathways[[i]] <- read.csv(paste0("./data/metabolicPathways/", path[i]))[,1]
  pathways[[i]] <- pathways[[i]][pathways[[i]] != ""]
}
names(pathways) <- path
```
### Processing data toi 

```{r}
dir.create("output")


Liver<- Liver %>%
        as.data.frame()
colnames(Liver)[2] <- "Condition"
metabolites <- colnames(Liver[,3:length(Liver)])
```


### Summarizing the spline fits across the data set

```{r}
options(digits=5)
options(scipen = 5)
for (x in seq_along(metabolites)){
        tmp.met <- na.omit(data.frame(metabolites = Liver[,metabolites[x]], Condition = Liver$Condition))
        tmp.met2 <- tmp.met
        tmp.met2[,1] <- log(tmp.met2[,1])
        #################
        #Stats Testing
        ################
        anova.results <- aov(tmp.met2[,1] ~ as.factor(tmp.met2[,2]))
        kw.results <- kruskal.test(tmp.met2[,1] ~ as.factor(tmp.met2[,2]))
        pwtt.results <- pairwise.t.test(tmp.met2[,1], as.factor(tmp.met2[,2]), p.adjust.method = "none")
        sidak.results <- Sidak(pwtt.results$p.value[1:4,1])
        #################
        #Fitting Splines
        ################
        fit2 <- ss(tmp.met[,1], as.numeric(tmp.met[,2]), all.knots = TRUE, method = "ML")
        test <- Liver[,c("Condition", metabolites[x])] %>%
          group_by(Condition) %>%
          na.omit() %>%
          summarize_all(funs(mean))
        trend <- max(test[,2]) - test[1,2]
        if (trend[,1] > 0) {
            range <- max(test[,2]) -  test[1,2]
        } else{
            range <- min(test[,2]) - test[1,2] 
        }
        FC <- log(test[5,2]/test[1,2], 2)
        t50 <- range/2 + test[1,2]
        t50 <- t50[,1]
        out <- predict(fit2, x = t50)[,2]
        rate <- out/10
        GCV <- fit2$cv.crit
        deg <- fit2$df
        spar <- fit2$spar
        pen <- fit2$pen.crit
        ratio <- fit2$ratio
        lambda <- fit2$lambda
        anova.p <- summary(anova.results)[[1]][["Pr(>F)"]][1]
        kw.p <- kw.results$p.value
        T0vOther <- sidak.results$SidakP
        names(T0vOther) <- paste0("SidakP.", c("t0.5", "t1", "t3", "t10"))
        output <- c(T50 = out, M50 = t50, 
                    rate = rate, 
                    range = range[,1], 
                    FC = FC[,1], 
                    cv.crit = GCV, 
                    degF = deg, 
                    spar = spar, 
                    pen.crit = pen, 
                    ratio = ratio, 
                    lambda = lambda, 
                    anova.p = anova.p, 
                    kw.p = kw.p,
                    T0vOther)
        output <- as.data.frame(output)
        if (x == 1) {
          mat <- t(output)
        } else {
        mat <- rbind(mat, t(output))
        }
    }
rownames(mat) <- metabolites
mat <- as.data.frame(mat)
mat$anova.FDR <- p.adjust(mat$anova.p)
mat$kw.FDR <- p.adjust(mat$kw.p)
mat$scaled_T50 = -scale(mat[,1])

############################
#Loop through time comparison
#############################
time.places <- c("t0.5", "t1", "t3", "t10")

mat$tp.designation <- NA
for(i in seq_len(nrow(mat))) {
  pos <- which(mat[i,13:16] < 0.05)
  if (length(pos) == 0) {
    next()
  } else {
    time.placeholder <- min(pos)
    mat[i,]$tp.designation <- time.places[time.placeholder]
  }
}
write.csv(mat,"./output/Liver_fittedValues.csv")
```


## Urchin Plots


```{r}
mat <- read.csv("./output/Liver_fittedValues.csv", row.names = 1)
dir.create("output/urchin")
mat$tp.designation <- factor(mat$tp.designation, levels =  c("t0.5", "t1", "t3", "t10"))
color.pal <- brewer_pal(palette = "RdBu")(4)
color.pal[2] <- "#D6604D"
names(color.pal) <- c("t0.5", "t1", "t3", "t10")
for (i in 1:length(pathways)){
plot <- mat[rownames(mat) %in% pathways[[i]],]   
plot$names <- rownames(plot)

g <- ggplot(plot, aes(x=-scale(T50), y=FC, group = "names")) + 
    geom_hline(yintercept = 0, lty = 2) + 
    geom_vline(xintercept = 0, lty = 2) +
    geom_segment(aes(xend=-scale(T50), yend=FC, x=0, y=0, color = tp.designation)) + 
    geom_point() +
    geom_text_repel(data=plot, aes(label=paste(names))) + 
    scale_color_manual(values =color.pal, na.value = "#222222") + 
    guides(color = "none") +
    theme_classic() + 
    labs(x = "t50 (Z-score)", y="Metabolite Fold-change")  +
  scale_x_continuous(limits=c(-4,4), breaks=c(-4,-3,-2,-1,1,2,3,4)) + 
    scale_y_continuous(limits=c(-3,8), breaks = c(-4,-3,-2,-1,1,2,3,4,5,6,7,8)) 
 ggsave(paste0("output/urchin/", names(pathways)[i], "_Urchin.pdf"), g, height=5, width=5) 
}


for (i in 1:length(pathways)){
plot <- mat[rownames(mat) %in% pathways[[i]],]   
plot$names <- rownames(plot)

g <- ggplot(plot, aes(x=-scale(T50), y=FC, group = "names")) + 
    geom_hline(yintercept = 0, lty = 2) + 
    geom_vline(xintercept = 0, lty = 2) +
    geom_segment(aes(xend=-scale(T50), yend=FC, x=0, y=0, color = tp.designation)) + 
    geom_point() +
    geom_text_repel(data=plot, aes(label=paste(names))) + 
    scale_color_manual(values =color.pal, na.value = "grey") + 
    guides(color = "none") +
    theme_classic() + 
    labs(x = "t50 (Z-score)", y="Metabolite Fold-change")  +
    scale_y_continuous(limits=c(-3,8), breaks = c(-4,-3,-2,-1,1,2,3,4,5,6,7,8)) 
 ggsave(paste0("output/urchin/", names(pathways)[i], "_Urchin_noXcontrol.pdf"), g, height=5, width=5) 
}

for (i in 1:length(pathways)){
plot <- mat[rownames(mat) %in% pathways[[i]],]   
plot$names <- rownames(plot)

g <- ggplot(plot, aes(x=-scale(T50), y=FC, group = "names")) + 
    geom_hline(yintercept = 0, lty = 2) + 
    geom_vline(xintercept = 0, lty = 2) +
    geom_segment(aes(xend=-scale(T50), yend=FC, x=0, y=0, color = tp.designation)) + 
    geom_point() +
    geom_text_repel(data=plot, aes(label=paste(names))) + 
    scale_color_manual(values =color.pal, na.value = "grey") + 
    guides(color = "none") +
    theme_classic() + 
    labs(x = "t50 (Z-score)", y="Metabolite Fold-change")  
 ggsave(paste0("output/urchin/", names(pathways)[i], "_Urchin_noXcontrol_noYcontrol.pdf"), g, height=5, width=5) 
}

for (i in 1:length(pathways)){
plot <- mat[rownames(mat) %in% pathways[[i]],]   
plot$names <- rownames(plot)

g <- ggplot(plot, aes(x=scaled_T50, y=FC, group = "names")) + 
    geom_hline(yintercept = 0, lty = 2) + 
    geom_vline(xintercept = 0, lty = 2) +
    geom_segment(aes(xend=scaled_T50, yend=FC, x=0, y=0, color = tp.designation)) + 
    geom_point() +
    geom_text_repel(data=plot, aes(label=paste(names))) + 
    scale_color_manual(values =color.pal, na.value = "grey") + 
    guides(color = "none") +
    theme_classic() + 
    labs(x = "t50 (Z-score)", y="Metabolite Fold-change")  +
    scale_y_continuous(limits=c(-3,8), breaks = c(-4,-3,-2,-1,1,2,3,4,5,6,7,8)) 
 ggsave(paste0("output/urchin/", names(pathways)[i], "_Urchin_noXcontrol_overallScaleT50.pdf"), g, height=5, width=5) 
}

for (i in 1:length(pathways)){
plot <- mat[rownames(mat) %in% pathways[[i]],]   
plot$names <- rownames(plot)

g <- ggplot(plot, aes(x=scaled_T50, y=FC, group = "names")) + 
    geom_hline(yintercept = 0, lty = 2) + 
    geom_vline(xintercept = 0, lty = 2) +
    geom_segment(aes(xend=scaled_T50, yend=FC, x=0, y=0, color = tp.designation)) + 
    geom_point() +
    geom_text_repel(data=plot, aes(label=paste(names))) + 
    scale_color_manual(values =color.pal, na.value = "grey") + 
    guides(color = "none") + 
    theme_classic() + 
    labs(x = "t50 (Z-score)", y="Metabolite Fold-change")  
 ggsave(paste0("output/urchin/", names(pathways)[i], "_Urchin_noXcontrol_noYcontrol_overallScaleT50.pdf"), g, height=5, width=5) 
}
```


```{r}
mat <- read.csv("./output/Liver_fittedValues.csv", row.names = 1)
mat <- as.data.frame(mat)
mat$tp.designation <- factor(mat$tp.designation, levels =  c("t0.5", "t1", "t3", "t10"))

ggplot(mat, aes(x=-scale(T50), y=FC)) + 
    geom_hline(yintercept = 0, lty = 2) + 
    geom_vline(xintercept = 0, lty = 2) +
    geom_segment(aes(xend=-scale(T50), yend=FC, x=0, y=0, color = tp.designation)) + 
    theme_classic() + 
    labs(x = "t50 (Z-score)", y="Metabolite Fold-change")  +
    scale_y_continuous(limits=c(-3,8), breaks = c(-4,-3,-2,-1,1,2,3,4,5,6,7,8)) + 
  scale_color_manual(values =color.pal, na.value = "grey") 
ggsave("output/urchin/overall_Urchin_noXcontrol.pdf", height=5, width=6.5) 

ggplot(mat, aes(x=-scale(T50), y=FC)) + 
    geom_hline(yintercept = 0, lty = 2) + 
    geom_vline(xintercept = 0, lty = 2) +
    geom_segment(aes(xend=-scale(T50), yend=FC, x=0, y=0, color = tp.designation)) + 
    theme_classic() + 
  scale_color_manual(values =color.pal, na.value = "grey") + 
    labs(x = "t50 (Z-score)", y="Metabolite Fold-change")  
ggsave("output/urchin/overall_Urchin_noXcontrol_noYcontrol.pdf", height=5, width=6.5) 
```

##############
#Plotly

```{r}
mat$metabolite = rownames(mat)
overall <- ggplot(mat, aes(x=-scale(T50), y=FC, text = metabolite)) + 
              geom_hline(yintercept = 0, lty = 2) + 
              geom_vline(xintercept = 0, lty = 2) +
              geom_segment(aes(xend=-scale(T50), yend=FC, x=0, y=0, color = tp.designation)) + 
              theme_classic() + 
              scale_color_manual(values =color.pal, na.value = "grey") + 
              labs(x = "t50 (Z-score)", y="Metabolite Fold-change")  +
              scale_y_continuous(limits=c(-3,8), breaks = c(-4,-3,-2,-1,1,2,3,4,5,6,7,8)) 
p <- ggplotly(overall, tooltip=c("text", "-scale(T50)", "FC"))  

library(htmlwidgets)
saveWidget(p, "./output/p1.html", selfcontained = T)
```

## Global Kinetics graph fitting

```{r}
data2 <- as.data.frame(Liver)

for (i in 3:length(data2)) {
        data2[,i] <- log(data2[,i]/mean(data2[1:5,i]),2)
    }

melted <- reshape2::melt(data2[,2:ncol(data2)], id.vars = "Condition")
melted$value <- abs(melted$value)
melted2 <- melted %>%
        na.omit() %>%
        group_by(Condition, variable) %>%
        summarise(mean1 = median(value, na.rm = T)) %>%
      as.data.frame()

lower_ci <- function(mean, se, n, conf_level = 0.95){
  lower_ci <- mean - qt(1 - ((1 - conf_level) / 2), n - 1) * se
}
upper_ci <- function(mean, se, n, conf_level = 0.95){
  upper_ci <- mean + qt(1 - ((1 - conf_level) / 2), n - 1) * se
}

CI <- melted2 %>%
  group_by(Condition) %>%
  summarise(smean = mean(mean1, na.rm = TRUE),
            ssd = sd(mean1, na.rm = TRUE),
            count = n()) %>%
  mutate(se = ssd / sqrt(count),
         lower_ci = lower_ci(smean, se, count),
         upper_ci = upper_ci(smean, se, count))

t50 <- (CI$smean[5] - CI$smean[1])/2 + CI$smean[1]

fit2 <- ss(melted2[,3], melted2[,1], all.knots = TRUE, method = "ML")
out <- as.numeric(predict(fit2, x = t50))

ggplot(aes(x=Condition, y=mean1), data = melted2) + 
       # geom_boxplot(aes(group=Condition), outlier.alpha = 0) + 
  geom_errorbar(data = CI, 
                aes(x = Condition, y= smean, ymin = lower_ci, ymax = upper_ci)) + 
  geom_smooth(method = lm, 
              formula = y ~ splines::bs(x, df = 2, degree = 2, knots = 10), color = "red") + 
        ylab("Abs(Log2-fold Change)") + 
        theme_classic() + 
        theme(axis.title.x = element_blank()) 
ggsave("./output/globalKinetics_Liver.pdf", height=3, width = 4)
```

